twig:
    default_path: '%kernel.project_dir%/templates'
    #form_themes: ['bootstrap_5_layout.html.twig'] # accepte plusieurs thèmes
    globals:
        allCategories: '@App\Services\GlobalCategories'

when@test:
    twig:
        strict_variables: true

